sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

language: scala

matrix:
  include:
  # Code forfmat test
  - env: PROJECT=code-format
    jdk: oraclejdk8
    script: ./scalafmt --test
  # Scala 2.12 + code coverage test
  - env: SCALA_VERSION=2.12.4
    jdk: oraclejdk8
    script:
      - ./sbt ++$SCALA_VERSION "; coverage; test; coverageReport"
      - ./sbt coverageAggregate && bash <(curl -s https://codecov.io/bash)
  - env: SCALA_VERSION=2.13.0-M2
    jdk: oraclejdk8
    script: ./sbt ++$SCALA_VERSION test
  - env: SCALA_VERSION=2.11.11
    jdk: oraclejdk8
    script: ./sbt ++$SCALA_VERSION test
